Param()

$ErrorActionPreference = "Stop"

function Backup-IfChanged($path) {
  if (Test-Path $path) {
    $bak = "$path.bak"
    if (-not (Test-Path $bak)) {
      Copy-Item $path $bak -Force
    }
  }
}

Write-Host "== PPPP Process Guardrails Patch =="

# 1) FEATURE_FLAGS in src/config.js einfügen (idempotent)
$cfgPath = "src/config.js"
if (Test-Path $cfgPath) {
  $cfg = Get-Content $cfgPath -Raw
  if ($cfg -notmatch "export\s+const\s+FEATURE_FLAGS") {
    Backup-IfChanged $cfgPath
    $insertion = @"
// --- Feature Flags (safe defaults) ---
export const FEATURE_FLAGS = { SPRITES_BETA: false, SIMULATION_V2: true };
"@
    Add-Content -Path $cfgPath -Value "`r`n$insertion"
    Write-Host "FEATURE_FLAGS in src/config.js hinzugefügt."
  } else {
    Write-Host "FEATURE_FLAGS bereits vorhanden – übersprungen."
  }
} else {
  Write-Warning "src/config.js nicht gefunden – übersprungen."
}

# 2) version.extra.js erzeugen/aktualisieren
$buildId = (New-Guid).Guid.Substring(0,8)
$ts = Get-Date -Format "yyyy-MM-dd HH:mm:ssK"
$verJs = @"
// Auto-generated by apply-patch.ps1
export const BUILD_INFO = { build: 'dev', id: '$buildId', stamped: '$ts' };
"@
New-Item -ItemType Directory -Force -Path "src" | Out-Null
Set-Content -Path "src/version.extra.js" -Value $verJs -Encoding UTF8
Write-Host "src/version.extra.js geschrieben."

# 3) PR-Template
New-Item -ItemType Directory -Force -Path ".github" | Out-Null
$pr = @"
## Was ist enthalten?
- [ ] Feature Flags / Beta-Toggle
- [ ] Keine Breaking Changes
- [ ] Version/Build im Menü aktualisiert (falls relevant)

## Tests
- [ ] npm start läuft
- [ ] Smoke-Test: Menü, Start, Pause

## Notes
"@
Set-Content -Path ".github/pull_request_template.md" -Value $pr -Encoding UTF8
Write-Host ".github/pull_request_template.md aktualisiert."

# 4) CHANGELOG.md
$entry = @"
## $(Get-Date -Format yyyy-MM-dd) – Patch: Feature-Flags + Prozess
- Add FEATURE_FLAGS in src/config.js (SPRITES_BETA=false, SIMULATION_V2=true)
- Add src/version.extra.js (BUILD_INFO)
- Add PR-Template
- Add apply-patch scripts (idempotent)
"@
if (Test-Path "CHANGELOG.md") {
  Add-Content -Path "CHANGELOG.md" -Value "`r`n$entry"
} else {
  Set-Content -Path "CHANGELOG.md" -Value "# Changelog`r`n$entry"
}
Write-Host "CHANGELOG.md aktualisiert."

Write-Host "== Fertig. Bitte committen: =="
Write-Host "   git add -A"
Write-Host "   git commit -m 'chore: add feature flags + build info + pr template'"
